import type { Locale } from "@/lib/feedback/config";

// French copy is a first draft. Have it reviewed before launch.
export const STRINGS = {
  en: {
    launcher: "Feedback",
    title: "Give us feedback",
    subtitle: "Tell us how we could make IST Legal more useful for your legal work.",
    close: "Close",
    back: "Back",
    titlePlaceholder: "Give it a short title",
    emailPlaceholder: "Your email address (optional)",
    takeScreenshot: "Take screenshot",
    retakeScreenshot: "Retake",
    capturing: "Capturing…",
    screenshotAdded: "Screenshot attached",
    removeScreenshot: "Remove screenshot",
    screenshotFailed: "Couldn't capture the screen. You can still send your feedback without it.",
    send: "Send",
    sending: "Sending…",
    titleRequired: "Add a short title so we know what it's about.",
    sendFailed: "Your feedback didn't send. Check your connection and try again.",
    thanksTitle: "Thank you — your feedback has been sent.",
    thanksBody: "The IST Legal team reads every message. It helps us decide what to fix and build next.",
    sendMore: "Send more feedback",
    done: "Done",
    confidential: "Please leave out client names and confidential case details.",
  },
  fr: {
    launcher: "Avis",
    title: "Donnez-nous votre avis",
    subtitle: "Dites-nous comment rendre IST Legal plus utile pour votre travail juridique.",
    close: "Fermer",
    back: "Retour",
    titlePlaceholder: "Un titre court",
    emailPlaceholder: "Votre adresse e-mail (facultatif)",
    takeScreenshot: "Capture d’écran",
    retakeScreenshot: "Reprendre",
    capturing: "Capture…",
    screenshotAdded: "Capture d’écran jointe",
    removeScreenshot: "Retirer la capture",
    screenshotFailed: "Impossible de capturer l’écran. Vous pouvez quand même envoyer votre avis.",
    send: "Envoyer",
    sending: "Envoi…",
    titleRequired: "Ajoutez un titre court pour que nous sachions de quoi il s’agit.",
    sendFailed: "Votre avis n’a pas été envoyé. Vérifiez votre connexion et réessayez.",
    thanksTitle: "Merci — votre avis a bien été envoyé.",
    thanksBody: "L’équipe IST Legal lit chaque message. Cela nous aide à décider quoi corriger et construire ensuite.",
    sendMore: "Envoyer un autre avis",
    done: "Terminé",
    confidential: "Merci de ne pas inclure de noms de clients ni de détails confidentiels.",
  },
} satisfies Record<Locale, Record<string, string>>;

export type Strings = (typeof STRINGS)["en"];
